from django.urls import path
from .views import (
    RegisterView,
    LoginView,
    MeView,
    UpdateUserView,
    CreatePickupView,
    PickupListView,
    DriverPickupsListView,
    CancelPickupView,
    ProductListView,
    CreateDriverDetailsView,
    RetrieveDriverDetailsView,
    UpdateDriverDetailsView,
    DriverDetailsListView,
    AvailablePickupsView,
    AcceptPickupView,
    ReportCreateView,
    DriverReportsListView,
    BillCreateView,
    DriverBillsListView,
    UserBillsListView,
)
from .views_forgot_password import ForgotPasswordView

urlpatterns = [
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("auth/update/", UpdateUserView.as_view(), name="auth-update"),
    path("auth/forgot_password/", ForgotPasswordView.as_view()),
    path("pickups/", PickupListView.as_view(), name="pickup-list"),
    path("pickups/available/", AvailablePickupsView.as_view(), name="available-pickups"),
    path("pickups/driver/", DriverPickupsListView.as_view(), name="driver-pickups-list"),
    path("pickups/create/", CreatePickupView.as_view(), name="pickup-create"),
    path("pickups/<int:pk>/accept/", AcceptPickupView.as_view(), name="pickup-accept"),
    path("pickups/<int:pk>/cancel/", CancelPickupView.as_view(), name="pickup-cancel"),
    path("reports/create/", ReportCreateView.as_view(), name="report-create"),
    path("reports/driver/", DriverReportsListView.as_view(), name="driver-reports-list"),
    path("bills/create/", BillCreateView.as_view(), name="bill-create"),
    path("bills/driver/", DriverBillsListView.as_view(), name="driver-bills-list"),
    path("bills/user/", UserBillsListView.as_view(), name="user-bills-list"),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("driver-details/", DriverDetailsListView.as_view(), name="driver-details-list"),
    path("driver-details/create/", CreateDriverDetailsView.as_view(), name="driver-details-create"),
    path("driver-details/retrieve/", RetrieveDriverDetailsView.as_view(), name="driver-details-retrieve"),
    path("driver-details/update/", UpdateDriverDetailsView.as_view(), name="driver-details-update"),
]
