# Generated by Django 6.0 on 2025-12-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_icon',
            field=models.CharField(default='📦', max_length=10),
        ),
    ]
