# Generated by Django 6.0 on 2025-12-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('IT Waste', 'IT Waste'), ('Vehicle Scrap', 'Vehicle Scrap'), ('Household Scrap', 'Household Scrap'), ('Metal Scrap', 'Metal Scrap'), ('Plastic & Paper', 'Plastic & Paper'), ('E-Waste', 'E-Waste'), ('Appliance Scrap', 'Appliance Scrap'), ('Furniture Scrap', 'Furniture Scrap'), ('Glass Scrap', 'Glass Scrap'), ('Miscellaneous', 'Miscellaneous')], max_length=100),
        ),
    ]
