# Generated by Django 6.0 on 2025-12-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pickup_driver_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.driverdetails')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.pickup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
