# Generated by Django 6.0 on 2026-01-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bill_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pickup_photos/'),
        ),
    ]
