# Generated by Django 6.0 on 2026-01-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pickup_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='time_slot',
            field=models.CharField(choices=[('10-2pm', '10:00 AM - 2:00 PM'), ('5-8pm', '5:00 PM - 8:00 PM')], max_length=20),
        ),
    ]
